apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingclient-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingclient
  template:
    metadata:
      labels:
        app: shoppingclient
    spec:
      containers:
      - name: shoppingclient
        image: thato955/shopping.client
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: ASPNETCORE_ENVIROMENT
            value: Development
          - name:  ShoppingAPIUrl
            valueFrom:
              configMapKeyRef:
                name:  shoppingapi-configmap
                key: shoppingapi_url
          
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
---
kind: Service
apiVersion: v1
metadata:
  name:  shoppingclient-service
spec:
  type: NodePort
  selector:
    app:  shoppingclient
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000